#name: parrotpos
#description: A bill payment and top up app
#
#publish_to: "none" # Remove this line if you wish to publish to pub.dev
#
#version: 1.3.2+16
#
#environment:
#  sdk: ">=2.17.0 <3.0.0"
#
#dependencies:
#  crypto: ^3.0.1
#  card_swiper: ^2.0.4
#  carousel_slider: ^4.1.1
#  contacts_service: ^0.6.3
#  cupertino_icons: ^1.0.4
#  dotted_border: ^2.0.0+2
#  dotted_line: ^3.1.0
#  double_back_to_close: ^2.0.0
#  firebase_auth: ^4.0.1
##  firebase_auth: ^3.3.15
##  firebase_core: ^1.15.0
#  firebase_core: ^2.24.2
#  flash: ^2.0.3+2
#  auth_buttons: ^3.0.0
#  flutter:
#    sdk: flutter
#  flutter_otp_text_field: ^1.0.1
#  flutter_share: ^2.0.0
#  flutter_svg: ^1.0.3
#  font_awesome_flutter: ^10.1.0
#  get: ^4.6.5
#  get_storage: ^2.0.3
#  # http: ^0.13.4
#  image_cropper: ^1.5.1
#  image_picker: ^0.8.5
#  intl: ^0.17.0
#  loading_indicator: ^3.0.3
#  permission_handler: ^9.2.0
#  progress_state_button: ^1.0.4
#  shared_preferences: ^2.0.13
#  snack: ^2.0.0
#  # iconify_flutter: ^0.0.5
#
#  styled_text: ^7.0.0
#  webview_flutter: ^3.0.4
#  flutter_datetime_picker_plus: ^2.2.0
##  flutter_datetime_picker: ^1.5.1
#  flutter_slidable: ^1.2.0
#  flutter_time_picker_spinner: ^2.0.0
#  native_pdf_view: ^6.0.0+1
#  advance_pdf_viewer: ^2.0.1
#  socket_io_client: ^1.0.2
#  # flutter_io_socket: ^0.0.7
#  slide_countdown: ^0.2.3
#  qr_flutter: ^4.0.0
#  connectivity_plus: ^3.0.2
#  screenshot: ^2.1.0
#  path_provider: ^2.0.9
#  flutter_widget_from_html_core: ^0.8.5+3
#  qr_code_scanner: ^1.0.1
#  # flutter_html: ^2.2.1
#  # flutter_html: ^3.0.0-alpha.5
#  flutter_widget_from_html: ^0.8.5
#  shimmer: ^2.0.0
#  google_sign_in: ^6.0.2
#  sign_in_with_apple: ^4.3.0
#  the_apple_sign_in: ^1.1.1
#  url_launcher: ^6.0.12
#dev_dependencies:
#  flutter_lints: ^1.0.0
#  flutter_test:
#    sdk: flutter
#
#dependency_overrides:
#  path_drawing: ^1.0.0
#  platform: ^3.1.0
#  provider: ^6.0.4
##  firebase_core_platform_interface: 4.5.1
#  # webview_flutter: ^2.0.4
#  gallery_saver_plus: ^3.0.1
#  http: ^1.1.0
#  google_fonts: ^6.2.1
#
#
#flutter:
#  uses-material-design: true
#
#  assets:
#    - assets/images/onboarding/
#    - assets/images/logo/
#    - assets/images/referral/
#    - assets/images/favorite/
#    - assets/images/dashboard/
#    - assets/images/forgot_password/
#    - assets/images/wallet/
#    - assets/images/donation/
#    - assets/images/signup/
#    - assets/images/
#    - assets/images/server_upgrade.png
#    - assets/icons/
#    - assets/icons/earning_history/
#    - assets/icons/transaction_history/
#    - assets/icons/bill_payment/
#    - assets/icons/favorite/
#    - assets/icons/earning_wallet/
#    - assets/icons/notification/

name: parrotpos
description: A bill payment and top up app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.12+23

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  card_swiper: ^3.0.1
  carousel_slider: ^4.1.1
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.4
  dotted_border: ^2.0.0+2
  dotted_line: ^3.1.0
  double_back_to_close: ^2.0.0
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flash: ^3.1.0
  auth_buttons: ^3.0.0
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.0.1
  flutter_share: ^2.0.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  get_storage: ^2.0.3
  animated_text_kit: ^4.2.2
  # http: ^0.13.4
  #  image_cropper: ^4.0.1
  #  image_picker: ^1.0.8
  image_cropper: ^1.5.1
  image_picker: ^0.8.5
  intl: ^0.19.0
  loading_indicator: ^3.0.3
  permission_handler: ^11.3.1
  progress_state_button: ^1.0.4
  shared_preferences: ^2.0.13
  snack: ^2.0.0
  # iconify_flutter: ^0.0.5
  share_plus: ^4.5.3
  #  auto_scroll: ^0.2.0

  styled_text: ^8.1.0
  webview_flutter: ^3.0.4
  #  webview_flutter: ^4.0.0
  # flutter_datetime_picker_plus: ^2.0.1
  #  flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_slidable: ^3.1.0
  flutter_time_picker_spinner: ^2.0.0
  syncfusion_flutter_pdfviewer: ^20.3.54
  #  native_pdf_view: ^6.0.0+1
  advance_pdf_viewer: ^2.0.1
  flutter_pdfview: ^1.3.2
  socket_io_client: ^2.0.3+1
  # flutter_io_socket: ^0.0.7
  slide_countdown: ^1.6.1
  qr_flutter: ^4.0.0
  connectivity_plus: ^6.0.2
  screenshot: ^3.0.0
  path_provider: ^2.0.9
  #  flutter_widget_from_html_core: ^0.14.11
  #  flutter_widget_from_html_core: ^0.9.1
  flutter_widget_from_html_core: ^0.8.5+3
  qr_code_scanner: ^1.0.1
  # flutter_html: ^2.2.1
  # flutter_html: ^3.0.0-alpha.5
  #  flutter_widget_from_html: ^0.14.11
  #  flutter_widget_from_html: ^0.9.1
  flutter_widget_from_html: ^0.8.5
  app_settings: ^5.1.1
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19
  flutter_native_contact_picker: ^0.0.7
  scroll_to_index: ^3.0.1
  smooth_page_indicator: ^1.1.0
  device_info_plus:
  snappable_thanos: ^0.0.4

  shimmer: ^3.0.0
  #  shimmer_animation: ^2.1.0+1
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^5.0.0
  the_apple_sign_in: ^1.1.1
  #  url_launcher: ^6.0.12
  url_launcher: ^6.3.0
  just_audio: ^0.9.35
  firebase_core_platform_interface: ^4.6.0
  #  firebase_core_platform_interface: 4.5.2
  cached_network_image: ^3.3.0
  video_player: ^2.9.2
#  pdfx: ^2.6.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

#firebase_core_platform_interface:
#  dependency: "direct main"
#  description:
#    name: firebase_core_platform_interface
#    sha256: b63e3be6c96ef5c33bdec1aab23c91eb00696f6452f0519401d640938c94cba2
#    url: "https://pub.dev"
#  source: hosted
#  version: "4.6.0"

dependency_overrides:
  path_drawing: ^1.0.0
  platform: ^3.1.0
  provider: ^6.0.4
  #  firebase_core_platform_interface: 5.0.0
  firebase_core_platform_interface: ^4.6.0
  #  firebase_core_platform_interface: 4.5.1
  #  webview_flutter: ^2.0.4
  #  gallery_saver:
  gallery_saver: ^2.3.2
  google_fonts:
  fwfh_svg:
  fwfh_webview:
  photo_manager: ^3.0.0-dev.2
#  pdfx: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/permission/
    - assets/images/logo/
    - assets/images/referral/
    - assets/images/favorite/
    - assets/images/dashboard/
    - assets/images/forgot_password/
    - assets/images/wallet/
    - assets/images/donation/
    - assets/images/signup/
    - assets/images/
    - assets/images/server_upgrade.png
    - assets/icons/
    - assets/icons/earning_history/
    - assets/icons/transaction_history/
    - assets/icons/bill_payment/
    - assets/icons/favorite/
    - assets/icons/earning_wallet/
    - assets/icons/notification/
