class MainWalletReload {
  MainWalletReload({
    this.status,
    this.minReloadAmount,
    this.message,
    this.userDetails,
    this.banks,
  });
  int? status;
  var minReloadAmount;
  String? message;
  MainWalletUserDetails? userDetails;
  List<UserBank>? banks;

  MainWalletReload.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    minReloadAmount = json['min_reload_amount'];
    message = json['message'];
    userDetails = MainWalletUserDetails.fromJson(json['user_details']);
    banks = List.from(json['banks']).map((e) => UserBank.fromJson(e)).toList();
  }

  Map<String, dynamic> toJson() {
    final _data = <String, dynamic>{};
    _data['status'] = status;
    _data['min_reload_amount'] = minReloadAmount;
    _data['message'] = message;
    _data['user_details'] = userDetails!.toJson();
    _data['banks'] = banks!.map((e) => e.toJson()).toList();
    return _data;
  }
}

class MainWalletUserDetails {
  MainWalletUserDetails({
    required this.accountStatus,
    required this.currency,
    required this.mainWalletAmount,
    required this.earningWalletAmount,
  });
  String? accountStatus;
  String? currency;
  var mainWalletAmount;
  var earningWalletAmount;

  MainWalletUserDetails.fromJson(Map<String, dynamic> json) {
    accountStatus = json['account_status'];
    currency = json['currency'];
    mainWalletAmount = json['main_wallet_amount'];
    earningWalletAmount = json['earning_wallet_amount'];
  }

  Map<String, dynamic> toJson() {
    final _data = <String, dynamic>{};
    _data['account_status'] = accountStatus;
    _data['currency'] = currency;
    _data['main_wallet_amount'] = mainWalletAmount;
    _data['earning_wallet_amount'] = earningWalletAmount;
    return _data;
  }
}

class UserBank {
  UserBank({
    required this.fpxBankId,
    required this.name,
    required this.logo,
    required this.bgColor,
    required this.fontColor,
    required this.helpText,
    required this.minimumReloadAmount,
  });
  String? fpxBankId;
  String? name;
  String? logo;
  String? bgColor;
  String? fontColor;
  String? helpText;
  var minimumReloadAmount;

  UserBank.fromJson(Map<String, dynamic> json) {
    fpxBankId = json['fpx_bank_id'];
    name = json['name'];
    logo = json['logo'];
    bgColor = json['bg_color'];
    fontColor = json['font_color'];
    helpText = json['help_text'];
    minimumReloadAmount = json['minimum_reload_amount'];
  }

  Map<String, dynamic> toJson() {
    final _data = <String, dynamic>{};
    _data['fpx_bank_id'] = fpxBankId;
    _data['name'] = name;
    _data['logo'] = logo;
    _data['bg_color'] = bgColor;
    _data['font_color'] = fontColor;
    _data['help_text'] = helpText;
    _data['minimum_reload_amount'] = minimumReloadAmount;

    return _data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WalletReloadInfoModel {
/*
{
  "status": 200,
  "message": "Hi, Test"
}
*/

  int? status;
  String? message;

  WalletReloadInfoModel({
    this.status,
    this.message,
  });
  WalletReloadInfoModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    return data;
  }
}
