import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/widgets/placeholder.dart';
import 'package:get/get.dart';
import 'package:parrotpos/screens/donation/fund_request_form.dart';
import 'package:parrotpos/widgets/buttons/gradient_button.dart';

import '../../style/colors.dart';
import '../../style/style.dart';

class DonationDetailScreen extends StatelessWidget {
  const DonationDetailScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          leading: IconButton(
              onPressed: () {
                Get.back();
              },
              icon: const Icon(CupertinoIcons.back)),
          centerTitle: true,
          elevation: 0,
          backgroundColor: Colors.white,
          title: Text(
            'Fund Result',
            style: kBlackExtraLargeStyle,
          ),
        ),
        body: SingleChildScrollView(
            child: Column(children: [
          const SizedBox(
            height: 30,
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Row(
              children: [
                Text(
                  "What is Donation in ParrotPos?",
                  style: kBlackDarkLargeStyle.copyWith(color: const Color(0xFF1076BE)),
                ),
              ],
            ),
          ),
          const SizedBox(
            height: 16,
          ),
          Container(
            margin: const EdgeInsets.symmetric(horizontal: 20),
            height: 154,
            decoration: const ShapeDecoration(
              image: DecorationImage(
                image: AssetImage("assets/images/donation/donation_detail_img.png"),
                fit: BoxFit.fill,
              ),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(10),
                  topRight: Radius.circular(10),
                ),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Text(
              '''At ParrotPOS, we believe in the power of giving back. That is why we have integrated a unique feature into our application that allows our users to make a difference with every transaction they make.\n \nWhether you're paying a bill or make prepaid reloads, a significant portion of the profits generated by ParrotPOS goes directly to charitable donations. The allocated amount is based on the service provider and it’s automatically earmarked for donation.\n \nIn this manner, by choosing ParrotPOS, you can not only enjoy a seamless and convenient payment experience for your bills, but also contribute to the betterment of society.\n''',
              style: kBlackLightMediumStyle.copyWith(fontWeight: FontWeight.w300, color: kBlack),
            ),
          ),
          const Divider(thickness: 0.30),
          FirstWidget(
            left: 30,
          ),
          SizedBox(
            height: 37,
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Row(
              children: [
                Text(
                  "What is “My Contribution”?",
                  style: kBlackDarkLargeStyle.copyWith(color: const Color(0xFF1076BE)),
                ),
              ],
            ),
          ),
          const SizedBox(
            height: 16,
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Text(
              'The "My Contribution" section on the application is where you can track and monitor the total amount you have contributed to donations over time. Every time you make a top-up or pay a bill using our app, your overall contribution is automatically updated under “My Contribution”.\n',
              style: kBlackLightMediumStyle.copyWith(fontWeight: FontWeight.w300, color: kBlack),
            ),
          ),
          const Divider(thickness: 0.30),
          FirstWidget(
            left: 30 + Get.width * 0.52,
          ),
          SizedBox(
            height: 37,
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Row(
              children: [
                Text(
                  "What are “Total Funds Raised”?",
                  style: kBlackDarkLargeStyle.copyWith(color: const Color(0xFF1076BE)),
                ),
              ],
            ),
          ),
          const SizedBox(
            height: 16,
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Text(
              'Total Funds Raised showcases the combined donations from all users, highlighting the remarkable achievements we accomplish together. It represents the sum of all the contributions made by users like you.\n \nCurrently, our milestone for Bandar Damai Home Care is set at RM10,000, which will directly support the important work of Bandar Damai Home Care in providing exceptional care and support to its residents.\n \nEach contribution, no matter how big or small, brings us closer to this milestone and closer to transforming lives.\n',
              style: kBlackLightMediumStyle.copyWith(fontWeight: FontWeight.w300, color: kBlack),
            ),
          ),
          const Divider(thickness: 0.30),
          SizedBox(
            height: 37,
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Row(
              children: [
                Text(
                  "Apply to Be Listed on Our Donation List.",
                  style: kBlackDarkLargeStyle.copyWith(color: const Color(0xFF1076BE)),
                ),
              ],
            ),
          ),
          const SizedBox(
            height: 16,
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Text(
              '''We understand the importance of supporting individuals and organizations who are in need of assistance. Hence, we have provided an opportunity for users to apply to be listed on our donation list, ensuring that we can extend our help to those who require it the most.\nIf you or someone you know is in need of financial assistance, we encourage you to apply through our "Fund Request Form."\n \nThe "Fund Request Form" is designed to make the application process simple and accessible. Whether it's for medical expenses, educational purposes, community projects, or any other valid cause, we welcome applications from individuals and organizations who require assistance.\n''',
              style: kBlackLightMediumStyle.copyWith(fontWeight: FontWeight.w300, color: kBlack),
            ),
          ),
          const Divider(thickness: 0.30),
          SizedBox(
            height: 37,
          ),
          GradientButton(
              text: "Funds Request Form",
              width: false,
              onTap: () {
                Get.to(FundRequestForm());
              },
              widthSize: Get.width,
              buttonState: null),
          SizedBox(
            height: 19,
          ),
          GradientButton(
              text: "Back",
              width: false,
              onTap: () {
                Get.back();
              },
              widthSize: Get.width,
              buttonState: null),
          SizedBox(
            height: 25,
          ),
        ])));
  }
}

class FirstWidget extends StatelessWidget {
  FirstWidget({super.key, required this.left});
  double left;
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Stack(children: [
        Container(
          margin: const EdgeInsets.only(left: 20, top: 35, bottom: 20),
          height: 64,
          decoration: const BoxDecoration(
            color: Colors.white,
            boxShadow: [
              BoxShadow(
                color: Color(0x11000000),
                blurRadius: 11,
                offset: Offset(0, 4),
                spreadRadius: 0,
              ),
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Row(
            children: [
              Container(
                width: Get.width * 0.5,
                padding: const EdgeInsets.only(left: 30),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      "My Contribution",
                      style: kBlackExtraSmallMediumStyle,
                    ),
                    Row(
                      children: [
                        Text(
                          "RM",
                          style: kBlackDarkMediumStyle.copyWith(fontSize: 10),
                        ),
                        const SizedBox(
                          width: 10,
                        ),
                        Text(
                          "0.10",
                          style: kGreenMediumStyle.copyWith(fontSize: 18),
                        ),
                        const Spacer(),
                        const SizedBox(
                          width: 20,
                        ),
                      ],
                    )
                  ],
                ),
              ),
              Container(
                margin: const EdgeInsets.symmetric(vertical: 10),
                color: Colors.grey.shade200,
                width: 1,
                height: 100,
              ),
              Container(
                  width: Get.width * 0.4,
                  padding: const EdgeInsets.only(left: 30),
                  child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [
                    Text(
                      "Total Fund Raised",
                      style: kBlackExtraSmallMediumStyle,
                    ),
                    Row(
                      children: [
                        Text(
                          "RM",
                          style: kBlackDarkMediumStyle.copyWith(fontSize: 10),
                        ),
                        const SizedBox(
                          width: 10,
                        ),
                        Text(
                          "57.45",
                          style: kGreenMediumStyle.copyWith(fontSize: 18),
                        ),
                        const Spacer(),
                        Container(
                          height: 26,
                          width: 26,
                          decoration: const ShapeDecoration(
                            image: DecorationImage(
                              image: AssetImage(
                                "assets/images/logo/logo_full.png",
                              ),
                            ),
                            shape: RoundedRectangleBorder(),
                            shadows: [],
                          ),
                        ),
                        const SizedBox(
                          width: 20,
                        ),
                      ],
                    ),
                  ])),
            ],
          ),
        ),
        Positioned(
          left: left,
          top: 30,
          child: Container(
            width: 118,
            height: 79,
            decoration: ShapeDecoration(
              shape: OvalBorder(
                side: BorderSide(width: 1, color: Color(0xFFE33629)),
              ),
            ),
          ),
        ),
      ]),
    );
  }
}
