class TermsAndConditions {
  TermsAndConditions({
    this.status,
    this.message,
    this.content,
  });
  int? status;
  String? message;
  String? content;

  TermsAndConditions.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    content = json['content'];
  }

  Map<String, dynamic> toJson() {
    final _data = <String, dynamic>{};
    _data['status'] = status;
    _data['message'] = message;
    _data['content'] = content;
    return _data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReferralTermsAndConditions {
/*
{
  "status": 200,
  "message": "Success",
  "content": "<p>Referral Terms &amp; Conditions</p>\n"
}
*/

  int? status;
  String? message;
  String? content;

  ReferralTermsAndConditions({
    this.status,
    this.message,
    this.content,
  });
  ReferralTermsAndConditions.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['content'] = content;
    return data;
  }
}
